trigger:
- main

pool:
  name: TestAgent

steps:

- checkout: self

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'

- script: |
    cd simple-maven-project
    mvn clean package
  displayName: 'Build Maven Project'